---
development:
  cloud_name: dzkigcywa
  api_key: '424657551725886'
  api_secret: IFO6gKHuIUqAsdSmOUZrx3eOABA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dzkigcywa
  api_key: '424657551725886'
  api_secret: IFO6gKHuIUqAsdSmOUZrx3eOABA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dzkigcywa
  api_key: '424657551725886'
  api_secret: IFO6gKHuIUqAsdSmOUZrx3eOABA
  enhance_image_tag: true
  static_image_support: false
